version: '3.8'

services:
  
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    #  - ./nginx/conf/certs:/etc/nginx/certs #certificates SSL (Secure Sockets Layer)
      - ./requirements/wordpress:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
  
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    ports:
      - "80:80"
    volumes:
      - ./requirements/wordpress:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env
    
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    ports:
      - "80:80"
    volumes:
      - home/ozasahin/Inception/srcs/requirements/mariadb/data:/var/lib/mysql:rw
    networks:
      - inception_network
    env_file:
      - .env
    
networks:
  inception_network:
    driver: bridge