services:
  
  nginx:
    image: nginx
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
      # - "80:80"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception_network
    depends_on:
      - wordpress
    restart: always
  
  wordpress:
    image: wordpress
    container_name: wordpress
    build: requirements/wordpress
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception_network
    env_file:
      - .env
    restart: always
    
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    ports:
      - "80:80"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
    restart: always

volumes:
  wordpress:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/ozasahin/data/wordpress
      o: bind
  mariadb:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/ozasahin/data/mariadb
      o: bind
    
networks:
  inception_network:
    driver: bridge