services:

  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception_network
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception_network
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always
    
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
    restart: always

  website:
    container_name: website
    build: requirements/bonus/website
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - inception_network
    restart: always
  
  # adminer:
  #   container_name: adminer
  #   build: requirements/bonus/adminer
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - inception_network
  #   depends_on:
  #     - mariadb
  #   restart:
  #     always

  # redis:
  #   container_name: redis
  #   build: requirements/bonus/redis
  #   networks:
  #     - inception_network
  #   ports:
  #     - '6379:6379'
  #   restart: always



volumes:
  wordpress:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/ozasahin/data/wordpress
      o: bind
  mariadb:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/ozasahin/data/mariadb
      o: bind

networks:
  inception_network:
    driver: bridge