version: 3.8

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "80:80"
    volumes:
      - ./requirements/wordpress:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress