# FROM debian:bullseye

# RUN apt-get update && \
# 	apt-get install -y redis-server php-redis && \
# 	apt-get clean  && \
# 	rm -rf /var/lib/apt/lists/*

# COPY ./conf/redis.sh /usr/local/bin

# RUN chmod +x /usr/local/bin/redis.sh

# ENTRYPOINT ["/usr/local/bin/redis.sh"]